package ar.edu.unlam.dominio;

public enum EquiposDeAfa {
	RIVER_PLATE, SAN_LORENZO, DEFENSA_Y_JUSTICIA, BELGRANO, ROSARIO_CENTRAL,LANUS,TALLERES,ESTUDIANTES,GODOY_CRUZ,ARGENTINOS_JUNIORS,RACING_CLUB,NEWELL, PLATENSE,INSTITUTO,TIGRE,VELEZ,BOCA_JUNIORS,SARMIENTO,CENTRAL_CORDOBA,COLON,BANFIELD,GIMNASIA,HURACAN,ATLETICO_TUCUMAN,BARRACAS_CENTRAL	
}
